### ISSUE TITLE
Favor bindings over autowiring

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#150]
using fixed services to bind, we allow users to use different services other then default

```yaml
services:
    msgphp.domain.doctrine_entity_manger: '@doctrine.orm.SOME_entity_manager'
    msgphp.domain.messenger_command_bus: '@messenger.bus.commands'
```

then we can simply bind them in vendor config using

```
bindings:
    Doctrine\ORM\EntityManagerInterface: '@msgphp.domain.doctrine_entity_manger'
```

Everybody happy :)
