### ISSUE TITLE
Revise security roles

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#192]
config

```
msgphp_user:
  security:
    default_roles: [ROLE_USER]
    role_providers:
      - MsgPhp\User\Infra\Security\RoleProvider\UserRoleProvider
```

rename interface to `MsgPhp\User\Infra\Security\RoleProvider\RoleProviderInterface`

add `UserRoleProvider` using `UserRoleRepositoryInterface`

add `ChainRoleProvider` 

add `DefaultRoleProvider`

update `UserMaker` to generate config instead of implementation

update bundle wiring based on config. Multiple `role_provider` and or `default_roles` services registers a chained role provider service

add interface alias for autowiring
