### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Stefan39** [msgphp/msgphp#325]
Hi,

before i have add my own User Entity on a API platform project and found this user-bundle which i would like to install.

But on installation with composer i got the error:

Invalid configuration for path "msgphp_user.class_mapping": Class "MsgPhp\User\User" must be configured to a mapped sub class value, got "App\Entity\User".

How can i resolve it?

**Comment by ro0NL** [comment]
Hi @Stefan39, the bundle requires a minimal configuration. To be found here;

https://github.com/symfony/recipes-contrib/blob/master/msgphp/user-bundle/0.10/config/packages/msgphp_user.php

This  file is created automatically when using Symfony Flex (with contrib recipes allowed).

In YAML it be

```yaml
# config/packages/msgphp_user.yaml

msgphp_user:
    class_mapping:
        MsgPhp\User\User: App\Entity\User
```
