### ISSUE TITLE
[user-bundle] deprecation notice on msgphp_user_id

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#332]
User Deprecated: The type "msgphp_user_id" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MsgPhp\User\Infrastructure\Doctrine\Type\UserIdType::requiresSQLCommentHint()."

Below is the key part of the generated User class

```php
// User.php
    /** @ORM\Id() @ORM\GeneratedValue() @ORM\Column(type="msgphp_user_id", length=191) */
    private $id;
```

**Comment by ro0NL** [comment]
Should be good now, can you confirm dev-master is OK?

**Comment by tacman** [comment]
I didn't regenerate anything, but simply updating composer.json to
'dev-master' gave:

 The service "security.context_listener.0" has a dependency on a
non-existen
!!    t service "MsgPhp\User\Infrastructure\Security\SecurityUserProvider".

**Comment by ro0NL** [comment]
Ah  i see :) there are a few more pending changes in master, e.g. `SecurityUserProvider` is renamed to `UserIdentityProvider`/

I'll make a release (with changelog) ASAP.

perhaps for now confirm by applying the patch manually...?

**Comment by tacman** [comment]
Not urgent for me, but I'll keep testing as you push out new versions.

**Comment by tacman** [comment]
SecurityUserProvider is renamed to UserIdentityProvider

Yep, that worked.  BTW, there's another deprecation in Symfony 4.3: 

    Configuring an encoder with "bcrypt" as algorithm is deprecated since Symfony 4.3, use "auto" instead.


So this is the first part of my security.yaml:

```yaml
security:
    encoders:
        MsgPhp\User\Infrastructure\Security\UserIdentity: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        msgphp_user: { id: MsgPhp\User\Infrastructure\Security\UserIdentityProvider }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: msgphp_user
```
