### ISSUE TITLE
Mapping error in prod mode

### ISSUE THREAD

**Issue by dvc** [msgphp/msgphp#92]
```
$ bin/console --env=dev d:m:info

 Found 29 mapped entities:

 [OK]   MsgPhp\User\Entity\User
 [OK]   MsgPhp\User\Entity\Credential\NicknameSaltedPassword
 [OK]   MsgPhp\User\Entity\UserSecondaryEmail
 [OK]   MsgPhp\User\Entity\Credential\Token
 [OK]   MsgPhp\User\Entity\Credential\EmailPassword
 [OK]   MsgPhp\User\Entity\Credential\Email
 [OK]   MsgPhp\User\Entity\Credential\Nickname
 [OK]   MsgPhp\User\Entity\UserRole
 [OK]   MsgPhp\User\Entity\Credential\EmailSaltedPassword
 [OK]   MsgPhp\User\Entity\Credential\NicknamePassword
 [OK]   App\Entity\User\User
...
```

```
$ bin/console --env=prod d:m:info

In MappingException.php line 75:
                                                                                                                
  No mapping file found named 'EmailPassword.orm.xml' for class 'MsgPhp\User\Entity\Credential\EmailPassword'.  
```

```
# src/Entity/User/User.php
<?php

namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Mapping\ClassMetadata;

use MsgPhp\Domain\Entity\Features\CanBeEnabled;
use MsgPhp\Domain\Entity\Fields\CreatedAtField;
use MsgPhp\Domain\Event\DomainEventHandlerInterface;
use MsgPhp\Domain\Event\DomainEventHandlerTrait;
use MsgPhp\User\Entity\Credential\EmailPassword;
use MsgPhp\User\Entity\Features\EmailPasswordCredential;
use MsgPhp\User\Entity\User as BaseUser;
use MsgPhp\User\UserIdInterface;

/**
 * @ORM\Entity
 * @final
 */
class User extends BaseUser implements DomainEventHandlerInterface
{
    use CanBeEnabled;
    use EmailPasswordCredential;
    use CreatedAtField;
    use DomainEventHandlerTrait;

    /**
     * @ORM\Column(type="simple_array")
     *
     * @var array
     */
    private $roles;

    public function __construct(
        UserIdInterface $id,
        string $email,
        string $password,
        bool $enabled = false,
        array $roles = ['ROLE_USER']
    )
    {
        parent::__construct($id);

        $this->enabled = $enabled;
        $this->credential = new EmailPassword($email, $password);
        $this->createdAt = new \DateTimeImmutable();

        $this->roles = $roles;
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('credential.email', new Email());
    }

    public function hasRole(string $role): bool
    {
        return in_array($role, $this->roles);
    }

    public function getRoles(): array
    {
        return $this->roles;
    }
}

```

```
# config/packages/doctrine.yaml

parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                MATCH_AGAINST: App\Extension\Doctrine\Query\Mysql\MatchAgainst
```

Symfony4
```
# composer.lock
...
            "name": "msgphp/domain",
            "version": "v0.1.5",
...
            "name": "msgphp/user",
            "version": "v0.1.5",
...
            "name": "msgphp/user-bundle",
            "version": "v0.1.5",
...
            "name": "doctrine/annotations",
            "version": "v1.6.0",
...
            "name": "doctrine/cache",
            "version": "v1.7.1",
...
            "name": "doctrine/common",
            "version": "v2.8.1",
...
            "name": "doctrine/dbal",
            "version": "v2.6.3",
...
            "name": "doctrine/doctrine-bundle",
            "version": "1.8.1",
...
            "name": "doctrine/orm",
            "version": "v2.6.0",
...
```
